package kz.kus.sa.tech.condition.exception;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    RESOURCE_IS_EXISTS,
    VALIDATION_ERROR,
    BAD_REQUEST,
    NO_USERS_TO_ASSIGN,
    INVALID_STATUS,
    NOT_ALLOWED,
    BUSINESS_ERROR,
    ACCESS_DENIED,
    EXECUTOR_SUBDIVISION_NOT_FOUND,
    TOO_MANY_EXECUTOR_SUBDIVISIONS,
    DECISION_NOT_FORMED,
}
